# Generated by Django 4.1.5 on 2023-01-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
